TRANSFER_ADAPTERS:
  basic:
    factory: giftless.transfer.basic_streaming:factory
    options:
      storage_class: giftless.storage.local_storage:LocalStorage
AUTH_PROVIDERS:
  - giftless.auth.jwt:
      options:
        private_key: test
        public_key: test
  - giftless.auth.allow_anon: read_only 
DEBUG: True
